## Configuration

### Overview

Re-core  the configuration data is kept under **~/re-core.edn** using The link:https://github.com/edn-format/edn[EDN] file format (Clojure's native data representation).

The configuration file is divided to the following sections:

*   Re-core properties like: ports, log settings.
*   Hypervisors where AWS, Openstack , Proxmox properties are set in matching sections.
*   Elasticsearch settings
*   SSH settings, mainly the private key path used to connect to remote instances.

**See the  <<Digitalocean>>, <<KVM>>, <<AWS>> sections for specific hypervisor configuration options.**

### Re-core

The Re-core section (situated on top) contains the configuration options of the server itself:
```clojure
{
 :re-core {
   :port 8082
   :log {
     :level :info
     :path "re-core.log"
   }
 }

 :elasticsearch {
   :host "localhost"
   :port 9200
 }

 :ssh {
   :private-key-path "/home/foo/.ssh/id_rsa"
 }

}
```

[options="header"]
.Mandatory Settings
|===
|Section|Property|Description|Comments

.1+| ports
| port
| Standard http port
| Used for non secured anonymous operations only

.2+| log
| level
| Default logging level
| Optional values include: trace, debug, info, error.

| path
| Where the log file is store locally
|

.2+| elasticsearch
| host
| The host Elasticsearch is running on
|

| port
| http API port (9200 by default)
|

.1+| ssh
| private-key-path
|
| Used by re-core to perform setup tasks on newly created VM's

|===

== Hypervisors

=== AWS

AWS configuration goes under the hypervisor/aws section in the link:#overview[configuration] file:

```clojure
{
  :hypervisor {
   :dev {
     :aws {
       :access-key ""
       :secret-key ""
       :ostemplates {
         :ubuntu-16.04 {:ami "" :flavor :debian}
       }
       :default-vpc {
          :vpc-id "vpc-123456" :subnet-id "subnet-123456" :assign-public true
        }
      }
    }
  }
}
```

[options="header"]
.AWS configuration
|===
| Section | Property | Description | Comments

| access-key
|
| AWS access key
|

| secret-key
|
| AWS API secret key
|

| ostemplates
|
| Mappings between system os key to AMI and flavor (redhat or debian).
|

.3+| default-vpc
| vpc-id
| The id of the VPC that will be used with EC2 instances.
|

| subnet-id
| The id of the subnet that will be used with EC2 instances.
|

| assign-public
| Whether to assign a public IP or not.
| If false then a VPN is used to access the internal VPC network.

|===


=== Digitalocean

link:https://www.digitalocean.com/[Digitalocean] is supported with the following configuration:


```clojure
:hypervisor {
  :dev {
    :digital-ocean {
      :token ""
      :ssh-key ""
      :ostemplates {
         :ubuntu-14.04  {:image "ubuntu-14-04-x64" :flavor :debian}
      }
     }
   }
}
```
.Digitalocean configuration

|===
|Section|Property|Description|Comments

| token
|
| Digitalocean authentication token
|

| ssh-key
|
| The ssh key id defined in Digitialocean for passwordless access to droplets.
|

| ostemplates
|
| Mapping from OS key to its Digitalocean image
| Please see link:#re-dock[https://github.com/re-ops/re-pack] on how to create a template

|===

=== KVM

link:http://www.linux-kvm.org/page/Main_Page[KVM] is supported with the following configuration:

```clojure
:hypervisor {
  :dev {
    :kvm  {
      :nodes {
         :remote {:username "ronen" :host "somehost" :port 22}
       }
      :ostemplates {
         :ubuntu-15.04 {:template "ubuntu-15.04" :flavor :debian}
      }
    }
  }
}
```
.KVM configuration
|===
|Section|Property|Description|Comments

| nodes
|
| Mapping from id to ssh connection details
| Please see link:#kvm-libvirt[libvirt] on how to setup authentication

| ostemplates
|
| Mapping from OS key to its KVM template
| Please see link:#packer[packer] on how to create a template

==== KVM Libvirt

Re-core uses link:https://libvirt.org/[libvirt] in order to access KVM hypervisor instances.

Libvirt uses the underlying ssh key setup in order to access remote hypervisors, this requires us to ssh-copy-id from the Re-core host into KVM hosts we would like to manage:

```bash
$ ssh-copy-id user@remote-kvm

```

Another issue is that we can't deploy Re-core itself as a VM within an hypervisor that we would like to manage due to link:https://wiki.libvirt.org/page/TroubleshootMacvtapHostFail[networking limitations] imposed by KVM (install Re-core outside any of the managed hosts).


=== Matrix

Currently supported and verified systems that Re-core works with:

.Supported hypervisors
|===
|Name|Versions|Operating systems|Comments
| AWS
|
| Ubuntu > = 16.x
|

| Digitalocean
|
| Ubuntu > = 16.x
|

| KVM
|
| Ubuntu > = 16.04
|
|===
