version: '2'
services:
  redis:
    ports:
      - "6379:6379"
    image: "redis:alpine"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
    depends_on: 
      - redis
