version: '2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    volumes:
       - data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - http.port=9200
      - http.cors.allow-origin=http://localhost:1358
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
  dejavu:
    image: "appbaseio/dejavu"
    ports:
      - "1358:1358"
    depends_on:
      - elasticsearch

volumes:
    data:
      driver: local
