version: '2'
services:
  redis:
    ports:
      - "6379:6379"
    image: "redis:alpine"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - http.port=9200
      - http.cors.allow-origin=http://localhost:1358
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    depends_on:
      - redis
  dejavu:
    image: "appbaseio/dejavu"
    ports:
      - "1358:1358"
    depends_on:
      - elasticsearch
